---
title: Yoxi.tv
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: sharon@yoxi.tv
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
baseurl: ''
url: http://yoxi.tv
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
include:
- _pages
exclude:
- node_modules
- Gemfile
- Gemfile.lock
- bower.json
- package.json
- webpack.mix.js
- gulpfile.js
- yarn.lock
- mix-manifest.json
- vendor
gems:
- jekyll-feed
- jekyll-sitemap
