---
title: Yoxi.tv
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: sharon@yoxi.tv
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
background_images:
- image: assets/imgs/bg-imgs/Corner_Interests.jpg
  alt: placeholder
- image: assets/imgs/bg-imgs/Corner_Press.jpg
  alt: placeholder
- image: assets/imgs/bg-imgs/journey-02-video.jpg
  alt: placeholder
- image: assets/imgs/bg-imgs/video-slide-test.jpg
  alt: placeholder
- image: assets/imgs/bg-imgs/yoxi_astronaut.jpg
  alt: placeholder
- image: assets/imgs/bg-imgs/Yoxi_BG_BOLD.jpg
  alt: placeholder
- image: assets/imgs/bg-imgs/Yoxi_BG_Crowd.jpg
  alt: placeholder
- image: assets/imgs/bg-imgs/Yoxi_BG_Kyle.jpg
  alt: placeholder
- image: assets/imgs/bg-imgs/Yoxi_BG_Network.jpg
  alt: placeholder
- image: assets/imgs/bg-imgs/Yoxi_BG_SciFi.jpg
  alt: placeholder
- image: assets/imgs/bg-imgs/Yoxi_BG_Sewing_2.jpg
  alt: placeholder
- image: assets/imgs/bg-imgs/Corner_Interests.jpg
  alt: placeholder
- image: assets/imgs/bg-imgs/Corner_Press.jpg
  alt: placeholder
- image: assets/imgs/bg-imgs/journey-02-video.jpg
  alt: placeholder
- image: assets/imgs/bg-imgs/video-slide-test.jpg
  alt: placeholder
baseurl: ''
url: http://yoxi.tv
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
include:
- _pages
exclude:
- node_modules
- Gemfile
- Gemfile.lock
- bower.json
- package.json
- webpack.mix.js
- gulpfile.js
- yarn.lock
- mix-manifest.json
- vendor
gems:
- jekyll-feed
- jekyll-sitemap
