# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yoxi.tv
email: sharon@yoxi.tv
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yoxi.tv" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

include:
  - _pages
exclude:
  - node_modules
  - Gemfile
  - Gemfile.lock
  - bower.json
  - package.json
  - webpack.mix.js
  - gulpfile.js
  - yarn.lock
  - mix-manifest.json
  - vendor

# Plugin settings
gems:
  - jekyll-feed
  - jekyll-sitemap
