---
title: Yoxi.tv
timezone: UTC
collections:
  bios:
    title: Bios
    output: false
  posts:
    title: Posts
    output: true
  sections:
    title: Sections
    output: false
  timeline:
    title: Timeline
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: bios
  values:
    question: ''
    prof_title: Founder
    image: ''
email: sharon@yoxi.tv
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
background_images:
- image: "/uploads/Yoxi_BG_Sewing_2.jpg"
- image: "/uploads/Yoxi_BG_Network.jpg"
- image: "/uploads/Yoxi_BG_SciFi.jpg"
- image: "/uploads/Yoxi_BG_Crowd.jpg"
- image: "/uploads/Yoxi_BG_Kyle.jpg"
- image: "/uploads/yoxi_astronaut.jpg"
- image: "/uploads/Yoxi_BG_BOLD.jpg"
- image: "/uploads/video-slide-test.jpg"
- image: "/uploads/journey-02-video.jpg"
- image: "/uploads/Corner_Press.jpg"
- image: "/uploads/Corner_Interests.jpg"
baseurl: 
url: http://yoxi.tv
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
include:
- _pages
exclude:
- node_modules
- Gemfile
- Gemfile.lock
- bower.json
- package.json
- webpack.mix.js
- gulpfile.js
- yarn.lock
- mix-manifest.json
- vendor
gems:
- jekyll-feed
- jekyll-sitemap
